### ISSUE TITLE
how do i install on opensuse?

### ISSUE THREAD

**Issue by Nagarjun-AR** [ocs-url/ocs-url#30] opened 2016-12-03 18:55 UTC
There seems to be no separate package for opensuse users.
Which should i download and how to install it on my opensuse KDE 42.2 [leap]?

**Comment by akiraohgaki** [comment] 2017-03-05 20:12
Sorry for late reply.

You can install the program from RPM file.
Just click the downloaded RPM file and continue installation with package manager.

If you like terminal:

    # zypper insall qt5-qtbase qt5-qtbase-gui qt5-qtsvg qt5-qtdeclarative qt5-qtquickcontrols
    # rpm -i /path/to/ocs-url*.rpm

**Comment by beurtbalkje** [comment] 2017-03-12 08:45
That won't do, I'm sorry to say.  OpenSUSE and Fedora have different naming conventions. You're zypper command should have been:
`sudo zypper install libqt5-qtbase-common-devel libqt5-qtbase-devel libqt5-qtsvg-devel libqt5-qtdeclarative-devel libqt5-qtdeclarative-tools libqt5-qtquickcontrols`
And installing a rpm from Fedora with your rpm command, gives openSUSE users something like this:
`~/Downloads> sudo rpm -i ocs-url-3.0.0-1.fc20.x86_64.rpm
root's password:                                                                                                                                                                
fout: Failed dependencies:                                                                                                                                                      
        qt5-qtbase >= 5.2.0 is needed by ocs-url-3.0.0-1.fc20.x86_64                                                                                                            
        qt5-qtbase-gui >= 5.2.0 is needed by ocs-url-3.0.0-1.fc20.x86_64                                                                                                        
        qt5-qtdeclarative >= 5.2.0 is needed by ocs-url-3.0.0-1.fc20.x86_64                                                                                                     
        qt5-qtquickcontrols >= 5.2.0 is needed by ocs-url-3.0.0-1.fc20.x86_64                                                                                                   
        qt5-qtsvg >= 5.2.0 is needed by ocs-url-3.0.0-1.fc20.x86_64 `

With zypper you can install the rpm package but only by ignoring 1 missing dependancy: qt5-qtbase. On my System (Leap 42.2 with plasma 4.8) installing several different plasmoids from store.kde.org is working, but with a bad result: not one of them is working. 

 So would you please produce an OpenSUSE rpm file with the right specs?

**Comment by beurtbalkje** [comment] 2017-03-12 09:08
In addition installing ocs-url with 

> sudo rpm -i ocs-url-3.0.0-1.fc20.x86_64.rpm -nodeps

> 

 has the same effect as described. Can anyone reproduce this?

**Comment by Joshbeyer** [comment] 2017-03-12 20:34
beurtbalkje Can you explain how to do this? I tried all last night to get ocs-url installed on opensuse tumbleweed and it didn't work. This morning it did randomly but after rebooting I had an issue cause me to have to reinstall because apparently I added some bad repositories from leap and main which broke firefox, zypper, and all the software packages. So I know it can be done, I just need to know how to do it the proper way. I have it installed now, but it doesn't work.

**Comment by Joshbeyer** [comment] 2017-03-12 21:14
nvm, apparently you just have to wait like an hour and it will start working... odd..

**Comment by akiraohgaki** [comment] 2017-03-13 01:19
RPM for openSUSE now available.
https://www.linux-apps.com/p/1136805/

Leap 42.1 or higher required.

**Comment by akiraohgaki** [comment] 2017-03-13 02:04
How to install:

Please see ocs-url description about installation on openSUSE.
https://www.linux-apps.com/p/1136805/

About plasmoids:

ocs-url has nothing to additional work for plasmoids, only install.
So if older or newer plasmoid does't work on your plasma version, try to report the issue to the plasmoid developer.

**Comment by akiraohgaki** [comment] 2017-03-13 02:10
@Nagarjun-AR @beurtbalkje @Joshbeyer
I hope you get RPM for opensuse and enjoy.
For now, I close this issue about package for openSUSE.

**Closed by akiraohgaki** 2017-03-13 02:10 UTC
